config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  
  root to: "products#index"
  resources :order_lines, only: [:create, :destroy]
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  concern :commentable do
    resources :comments, only: [:create, :destroy, :update]
  end
  resources :users, only: [:show, :index], concerns: :commentable do
    member do
      get "edit_my_profile", to: "users#edit_my_profile"
      put "update_my_profile", to: "users#update_my_profile"
    end
  end
  resources :products, only: [:index, :show], concerns: :commentable do
    member do
      put "like", to: "products#like"
      put "dislike", to: "products#dislike"
    end
  end
  resources :orders, only: [:destroy, :update], concerns: :commentable do
  end
  namespace :admin do
    resources :products, concerns: :commentable
    resources :orders, only: [:index, :show]
    resources :product_logs, only: :index
    resources :users, concerns: :commentable do 
      member do
        get "edit_my_profile", to: "users#edit_my_profile"
        put "update_my_profile", to: "users#update_my_profile"
      end
    end
    get "comments/not_approved", to: "comments#not_approved"
    get "/" => "products#index"
  end
  resource :carts, only: [:show], path: 'cart'

  #API Namespace
  use_doorkeeper do
    skip_controllers :authorizations, :applications,
      :authorized_applications
  end
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      get "/" => "products#index"
      devise_for :users, controllers: {
        registrations: 'api/v1/users/registrations',
      }, skip: [:sessions, :password]
      resources :order_lines, only: [:create, :destroy]
      resources :products do
        member do
          put "like", to: "products#like"
          put "dislike", to: "products#dislike"
        end
      end
      resources :orders, only: [:destroy, :show, :index], concerns: :commentable do
        member do
          put "checkout", to: "orders#checkout"
        end
      end
      resource :carts, only: [:show], path: 'cart'
      resource :passwords do
        member do
          post "request_change", to: "passwords#request_change"
          post "reset", to: "passwords#reset"
        end
      end
    end
  end
end

app/views/shared/_flash.html.erb
<%if notice %>
<div class="ui info message sixteen wide column" style="margin-top: 15px">
  <div class="header"><%= notice %></div>
</div>
<%end%>
<%if alert %>
  <div class="ui warning message sixteen wide column" style="margin-top: 15px">
  <div class="header">Oops! We found the following errors:</div>
  <ul class="list">
    <% if alert.is_a?(String) %>
    <li><%= alert %></li>
    <% else %>
      <% alert.each do |err|%>
        <li><%= err %></li>
      <% end %>
    <% end %>
  </ul>
</div>
<% end %>

app/views/shared/_footer.html.erb
<br>
<div style="text-align: center">
  <h4>All Rights Reserved | Merlos SnackStore</h4>
</div>

app/views/shared/_navbar.html.erb
<nav>
<div class="ui secondary  menu">
  <%= link_to "- Merlos Snackstore - #{current_user.role_name if user_signed_in?}", root_path, class: 'item' %>
  <% if !user_signed_in? || current_user.regular?%>
    <%= link_to 'Cart', carts_path, class: 'item' %>
    <%= link_to 'All Users', users_path, class: 'item' %>
  <%end%>
  <% if user_signed_in? && current_user.admin?%>
    <%= link_to 'Orders Log', admin_orders_path, class: 'item' %>
    <%= link_to 'Product Log', admin_product_logs_path , class: 'item' %>
    <%= link_to 'New Product', new_admin_product_path , class: 'item' %>
  <%end%>
  <% if user_signed_in? && !current_user.regular?%>
    <%= link_to 'New User', new_admin_user_path , class: 'item' %>
    <%= link_to 'Not Approved Comments', admin_comments_not_approved_path , class: 'item' %>
  <%end%>
  <div class="right menu">
    <% if user_signed_in? %>
      <% if current_user.regular? %>
        <%= link_to('My Profile', current_user, class: 'item') %>
      <% else %>
        <%= link_to('My Profile', [:admin, current_user], class: 'item') %>
        <%= link_to 'All Users', admin_users_path, class: 'item' %>
      <% end %>
      <%= link_to('Log Out', logout_path, method: :delete, class: 'negative ui item') %>
    <% else %>
      <%= link_to('Log In', login_path, class: 'positve ui item') %>  
    <% end %>
    </div>
  </div>
</div>
</nav>