config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  
  root to: "products#index"
  resources :order_lines, only: [:create, :destroy]
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  concern :commentable do
    resources :comments, only: [:create, :destroy, :update]
  end
  resources :users, only: [:show, :index], concerns: :commentable do
    member do
      get "edit_my_profile", to: "users#edit_my_profile"
      put "update_my_profile", to: "users#update_my_profile"
    end
  end
  resources :products, only: [:index, :show], concerns: :commentable do
    member do
      put "like", to: "products#like"
      put "dislike", to: "products#dislike"
    end
  end
  resources :orders, only: [:destroy, :update], concerns: :commentable do
  end
  namespace :admin do
    resources :products, concerns: :commentable
    resources :orders, only: [:index, :show]
    resources :product_logs, only: :index
    resources :users, concerns: :commentable do 
      member do
        get "edit_my_profile", to: "users#edit_my_profile"
        put "update_my_profile", to: "users#update_my_profile"
      end
    end
    get "comments/not_approved", to: "comments#not_approved"
    get "/" => "products#index"
  end
  resource :carts, only: [:show], path: 'cart'

  #API Namespace
  use_doorkeeper do
    skip_controllers :authorizations, :applications,
      :authorized_applications
  end
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      get "/" => "products#index"
      devise_for :users, controllers: {
        registrations: 'api/v1/users/registrations',
      }, skip: [:sessions, :password]
      resources :order_lines, only: [:create, :destroy]
      resources :products do
        member do
          put "like", to: "products#like"
          put "dislike", to: "products#dislike"
        end
      end
      resources :orders, only: [:destroy, :show, :index], concerns: :commentable do
        member do
          put "checkout", to: "orders#checkout"
        end
      end
      resource :carts, only: [:show], path: 'cart'
      resource :passwords do
        member do
          post "request_change", to: "passwords#request_change"
          post "reset", to: "passwords#reset"
        end
      end
    end
  end
end

app/models/api/v1/product.rb
# frozen_string_literal: true

class Api::V1::Product < ApplicationRecord
end

app/models/product.rb
# frozen_string_literal: true

# Product model
class Product < ApplicationRecord
  acts_as_paranoid
  acts_as_votable
  paginates_per 12
  has_one_attached :image
  has_many :order_lines
  has_many :orders, through: :order_lines
  has_many :product_tags
  has_many :tags, through: :product_tags
  has_many :product_logs
  has_many :comments, as: :commentable
  validates :sku, presence: true, uniqueness: true
  validates :name, :description, :price, :stock, presence: true
  validates :price, :stock, :cached_votes_up, :cached_votes_down, numericality: { greater_than_or_equal_to: 0 }
  after_update :check_for_low_stock

  def image_path
    ActiveStorage::Blob.service.send(:path_for, image.key) if image.attached?
  end

  # Default scope to sort by name ascendingly
  def self.default_scope
    order(name: :asc)
  end

  # Scope because of soft delete
  def self.not_deleted
    where('deleted_at IS NULL')
  end

  # Scope for customer side
  def self.active
    where('active = true AND deleted_at IS NULL')
  end

  private

  def check_for_low_stock
    if stock.between?(1, 3)
      NotifyOnLowStockJob.perform_later(id) if cached_votes_up > 0
    end
  end
end

app/controllers/admin/products_controller.rb
# frozen_string_literal: true

# Controller for products display and CRUD from admin
class Admin::ProductsController < ApplicationController
  include Commentable
  include Filterable
  before_action :authenticate_user!
  before_action :authorize_user
  before_action :set_product, except: %i[index new create]
  before_action :set_tag, only: %i[index edit new update create]

  # GET /admin/products
  # /admin/ (admin root path)
  def index
    @products = Product.not_deleted.page params[:page]
    @products = filter_resource(@products)
    @products = ProductDecorator.decorate_collection(@products.with_attached_image)
    @order_line = current_order.order_lines.new
  end

  # GET /admin/products/:id
  def show
    @commentable = @product
    prepare_comments
  end

  # GET /admin/products/new
  def new
    @product = Product.new
  end

  # GET /admin/products/:id/edit
  def edit; end

  # POST /admin/products
  def create
    @product = Product.new(product_params)
    if @product.save
      @product.image.attach(product_params[:image]) if product_params[:image]
      redirect_to @product, notice: 'Product was successfully created.'
    else
      redirect_to new_admin_product_path, alert: @product.errors.full_messages
    end
  end

  # PUT /admin/products/:id
  def update
    ProductChangeLogger.new(@product, product_params, current_user).call
    if @product.update(product_params)
      if product_params[:image]
        @product.image.purge
        @product.image.attach(product_params[:image])
      end
      redirect_to @product, notice: 'Product was successfully updated.'
    else
      redirect_to edit_admin_product_path, alert: @product.errors.full_messages
    end
  end

  # DELETE /admin/products/:id
  def destroy
    @product.image.purge
    if @product.destroy
      redirect_to root_path, notice: 'Product was successfully destroyed.'
    else
      redirect_to root_path, alert: @product.errors.full_messages
    end
  end

  private

  def authorize_user
    authorize [:admin, Product]
  end

  # Sets product to work with based on id
  def set_product
    @product = Product.find(params[:id]).decorate
  end

  # Sets all tags for display
  def set_tag
    @tags = Tag.all
  end

  # Filters strong product params
  def product_params
    if current_user.admin?
      params.require(:product).permit(:sku, :name, :description, :price, :stock, :active, :image, tag_ids: [])
    elsif current_user.support?
      params.require(:product).permit(:name, :description, :stock, :active, :image, tag_ids: [])
    end
  end

  # Filters strong search parameters (not required)
  def search_params
    params.fetch(:search, {}).permit(:name, :tag)
  end

  # Filters filter(sorting) parameters
  def filter_param
    params.permit(:filter)
  end
end

app/controllers/api/v1/products_controller.rb
# frozen_string_literal: true

class Api::V1::ProductsController < Api::V1::ApplicationController
  include Filterable
  before_action :doorkeeper_authorize!, except: %i[index show]
  before_action :set_product, except: %i[index create]

  def index
    @products = ::Product.active.page(params[:page])
    @products = filter_resource(@products)
    @products = ::ProductRepresenter.for_collection.new(@products.includes(:tags, :comments).with_attached_image)
    render json: { products: @products }, exclude: [:comments]
  end

  def show
    if @product.active && @product.deleted_at.nil?
      render json: ::ProductRepresenter.new(@product)
    else
      render json: { error: { id: "Record couldn't be found" } }, status: :not_found
    end
  end

  def create
    @product = ::Product.new(product_params)
    if @product.save
      @product.image.attach(product_params[:image]) if product_params[:image]
      render json: ::ProductRepresenter.new(@product), status: :created, location: @product
    else
      render json: { error: @product.errors }, status: :unprocessable_entity
    end
  end

  def update
    if @product.update(product_params)
      if product_params[:image]
        @product.image.purge
        @product.image.attach(product_params[:image])
      end
      render json: ::ProductRepresenter.new(@product)
    else
      render json: { error: @product.errors }, status: :unprocessable_entity
    end
  end

  def destroy
    @product.image.purge
    if @product.destroy
      render json: ::ProductRepresenter.new(@product), location: @product
    else
      render json: { error: @product.errors }, status: :unprocessable_entity
    end
  end

  def like
    if @product.upvote_by(current_user)
      render json: ::ProductRepresenter.new(@product), location: @product
    else
      render json: { error: @product.errors }, status: :unprocessable_entity
    end
  end

  def dislike
    if @product.downvote_by(current_user)
      render json: ::ProductRepresenter.new(@product), location: @product
    else
      render json: { error: @product.errors }, status: :unprocessable_entity
    end
  end

  private

  def set_product
    @product = ::Product.find(params[:id])
  end

  def set_tag
    @tags = Tag.all
  end

  def product_params
    params.require(:product).permit(:sku, :name, :description, :price, :stock, :active, :image, tag_ids: [])
  end

  def search_params
    params.fetch(:search, {}).permit(:name, :tag)
  end

  def filter_param
    params.permit(:filter)
  end
end

app/controllers/products_controller.rb
# frozen_string_literal: true

# Controller for products display
class ProductsController < ApplicationController
  include Commentable
  include Filterable
  before_action :authenticate_user!, except: %i[index show]
  before_action :authorize_user
  before_action :set_product, except: [:index]
  before_action :set_tag, only: [:index]
  before_action :set_new_order_line, only: %i[index show]

  # GET /products
  # / (root path)
  def index
    @products = Product.active.page(params[:page])
    @products = filter_resource(@products)
    @products = ProductDecorator.decorate_collection(@products.with_attached_image)
  end

  # GET /products/:id
  def show
    @commentable = @product
    prepare_comments
  end

  # PUT /products/:id/like
  def like
    @product.upvote_by(current_user)
    render 'vote.js'
  end

  # PUT /products/:id/dislike
  def dislike
    @product.downvote_by(current_user)
    render 'vote.js'
  end

  private

  def authorize_user
    authorize Product
  end

  # Sets a new order line for possible shopping
  def set_new_order_line
    @order_line = current_order.order_lines.new
  end

  # Sets product to work with based on id
  def set_product
    @product = Product.find(params[:id]).decorate
  end

  # Sets all tags for display
  def set_tag
    @tags = Tag.all
  end

  # Filters strong search parameters (not required)
  def search_params
    params.fetch(:search, {}).permit(:name, :tag)
  end

  # Filters filter(sorting) parameters
  def filter_param
    params.permit(:filter)
  end
end

app/views/admin/products/_filterbar.html.erb
<div class="ui text menu">
  <div class="header item">Filter By</div>
  <%= link_to "Name", admin_products_path(
    search: {
      tag: (params[:search][:tag] rescue nil),
      name: (params[:search][:name] rescue nil)
      }, 
    filter: 'name'
    ), remote: true, class: "item"%>
  <%= link_to "Popularity", admin_products_path(
    search: {
      tag: (params[:search][:tag] rescue nil), 
      name: (params[:search][:name] rescue nil)
      }, 
    filter: 'vote'
      ), remote: true, class: "item"%>
</div>

app/views/admin/products/_form.html.erb
<div class="ten wide column">
<div class="ui form">
<%= form_for [:admin, @product] do |form| %>
  <div class="field">
    <%= form.label :sku %>
    <%= form.text_field :sku, disabled: current_user.support?, required: true %>
  </div>
  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, autofocus: true, required: true%>
  </div>
  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, rows: 3, required: true%>
  </div>
  <div class="field five wide column">
    <%= form.label :price %>
    <%= form.number_field :price, min: 0, step: 0.01, disabled: current_user.support?, required: true %>
  </div>
  <div class="field five wide column">
    <%= form.label :stock %>
    <%= form.number_field :stock, min: 0 %>
  </div>
  <div class="inline field">
  <div class="ui toggle checkbox">
    <%= form.check_box :active %>
    <%= form.label :active %>
  </div>
  </div>
  <div class="inline field">
    <%= form.label :tags %>
    <% @tags.each do |tag| %>
       <label for="<%="tag_#{tag.id}"%>">
       <%= form.check_box :tag_ids, {multiple: true, id: "tag_#{tag.id}"}, tag.id, nil %>
       <%= tag.name %>
    <%end%>
  </div>
  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>
  <div class="actions">
    <%= form.submit class: 'ui primary button'%>
  </div>
<% end %>
</div>
</div>

app/views/admin/products/_product_card.html.erb
<div class="ui people shape">
  <div class="ui card">
    <div class="image"><%= image_tag(product.image.variant(resize: "220x220!")) if product.image.attached? %></div>
    <div class="content">
      <div class="header">
      <%= link_to truncate(product.name, length: 50), admin_product_path(product), class: "ui small header" %>
      </div>
      <div class="meta"><%= number_to_currency product.price %> |
      <%= product.active? %> | 
      <%= product.stock %> In Stock </div>
      <div class="description"><%= truncate(product.description, length: 70) %></div>
    </div>
    <div class="extra content">
        <span class="right floated">
            Likes: <span id = "likes_for_product_<%= product.id %>">
            <%= product.cached_votes_up %></span>
            Dislikes: <span id = "dislikes_for_product_<%= product.id %>">
            <%= product.cached_votes_down %></span>
        </span>
      </div>
    <div class="extra content">
      <span class="right floated">       
        <%= link_to 'Edit', edit_admin_product_path(product), class: 'positive ui button' %>
        <%= link_to 'Destroy', admin_product_path(product), method: :delete, 
        data: { confirm: 'Are you sure?' }, class: 'negative ui button' if current_user.admin? %>
      </span>
    </div>
  </div>
</div>

app/views/admin/products/_search.html.erb
<%= form_for :search, method: :get, remote: true  do |f|%>
  <div class="ui fluid icon input">
      <%= link_to "Clear", admin_products_path, remote: true, class: 'negative ui button' %>
    <%= f.text_field :name, placeholder: "Search Products...", autofocus: true %>
    <i class="search icon"></i>
  </div>
<%end%>

app/views/admin/products/_sidebar.html.erb
<aside>
<div class="ui vertical secondary menu">
<h1 style="margin-top: 50px">Tags</h1>
<%@tags.each do |tag|%>
  <%= link_to tag.name, admin_products_path(
    search: {
      tag: tag.name,
      ame: (params[:search][:name] rescue nil)
      }), 
      remote: true, class: 'item'%>
<%end%>
</div>
</aside>

app/views/admin/products/edit.html.erb
<div class="ten wide column">
<h1>Edit Product</h1>
</div>
<%= render 'form', product: @product %>

app/views/admin/products/index.html.erb
<div id="sidebar" class="two wide column">
  <%= render partial: "sidebar" %>
</div>
<div class="fourteen wide column">
  <div class="item">
    <%= render partial: 'search' %>
  </div>
  <h1>Products</h1>
  <div id="filterbar">
    <%= render partial: "filterbar" %>
  </div>
  <div id="grid">
    <%= render partial: "product_card", collection: @products, as: :product %>
  </div>
  <div style="margin-left: 33%">
    <%= paginate @products, remote: true %>
  </div>
</div>

app/views/admin/products/index.js.erb
(function init() {
  document.querySelector('#grid').innerHTML =
    '<%= escape_javascript(render(partial: "product_card", collection: @products, as: :product)) %>';
  document.querySelector('#sidebar').innerHTML =
    '<%= escape_javascript(render(partial: "sidebar")) %>';
  document.querySelector('#filterbar').innerHTML =
    '<%= escape_javascript(render(partial: "filterbar")) %>';
})()

app/views/admin/products/new.html.erb
<div class="ten wide column">
<h1>New Product</h1>
</div>
<%= render 'form', product: @product %>

app/views/admin/products/show.html.erb
<div class="ten wide column">
<h1>Product Details</h1>
</div>
<div class="ten wide column" id="product">
  <%= render partial: "product_card", locals: {product: @product} %>
</div>
<div class="ten wide column ui comments">
  <h3 class="ui dividing header">Comments</h3>
  <div id="comments">
    <%= render partial: 'comments/comment_block', collection: @comments, as: :comment %>
  </div>
  <%= render partial: 'comments/comment_form' %>
</div>