config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => "/sidekiq"
  
  root to: "products#index"
  resources :order_lines, only: [:create, :destroy]
  devise_for :users
  devise_scope :user do
    get 'login', to: 'devise/sessions#new'
    delete 'logout', to: 'devise/sessions#destroy'
  end
  concern :commentable do
    resources :comments, only: [:create, :destroy, :update]
  end
  resources :users, only: [:show, :index], concerns: :commentable do
    member do
      get "edit_my_profile", to: "users#edit_my_profile"
      put "update_my_profile", to: "users#update_my_profile"
    end
  end
  resources :products, only: [:index, :show], concerns: :commentable do
    member do
      put "like", to: "products#like"
      put "dislike", to: "products#dislike"
    end
  end
  resources :orders, only: [:destroy, :update], concerns: :commentable do
  end
  namespace :admin do
    resources :products, concerns: :commentable
    resources :orders, only: [:index, :show]
    resources :product_logs, only: :index
    resources :users, concerns: :commentable do 
      member do
        get "edit_my_profile", to: "users#edit_my_profile"
        put "update_my_profile", to: "users#update_my_profile"
      end
    end
    get "comments/not_approved", to: "comments#not_approved"
    get "/" => "products#index"
  end
  resource :carts, only: [:show], path: 'cart'

  #API Namespace
  use_doorkeeper do
    skip_controllers :authorizations, :applications,
      :authorized_applications
  end
  namespace :api, defaults: {format: :json} do
    namespace :v1 do
      get "/" => "products#index"
      devise_for :users, controllers: {
        registrations: 'api/v1/users/registrations',
      }, skip: [:sessions, :password]
      resources :order_lines, only: [:create, :destroy]
      resources :products do
        member do
          put "like", to: "products#like"
          put "dislike", to: "products#dislike"
        end
      end
      resources :orders, only: [:destroy, :show, :index], concerns: :commentable do
        member do
          put "checkout", to: "orders#checkout"
        end
      end
      resource :carts, only: [:show], path: 'cart'
      resource :passwords do
        member do
          post "request_change", to: "passwords#request_change"
          post "reset", to: "passwords#reset"
        end
      end
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

# Devise User model
class User < ApplicationRecord
  acts_as_paranoid
  paginates_per 12
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :access_grants,
           class_name: 'Doorkeeper::AccessGrant',
           foreign_key: :resource_owner_id,
           dependent: :delete_all

  has_many :access_tokens,
           class_name: 'Doorkeeper::AccessToken',
           foreign_key: :resource_owner_id,
           dependent: :delete_all
  has_one :profile
  has_many :orders
  has_many :product_logs, foreign_key: :admin_id
  has_many :comments
  has_many :comments, as: :commentable
  delegate :first_name, :last_name, :phone, :address, to: :profile, prefix: true, allow_nil: true
  delegate :full_name, to: :profile

  enum role_options: {
    0 => 'regular',
    1 => 'admin',
    2 => 'support_user'
  }
  validates :role, numericality: { in: role_options.keys }

  def self.authenticate(email, password)
    user = User.find_for_authentication(email: email)
    user.try(:valid_password?, password) ? user : nil
  end

  # To avoid cost of migrating admin column(boolean) to role column(integer)
  def regular?
    role == 0
  end

  def admin?
    role == 1
  end

  def support?
    role == 2
  end

  def role_name
    case role
    when 0
      'Regular'
    when 1
      'Admin'
    when 2
      'Support'
    end
  end

  # Shows only those not soft deleted
  def self.not_deleted
    where('deleted_at IS NULL')
  end
end

app/controllers/admin/users_controller.rb
# frozen_string_literal: true

class Admin::UsersController < ApplicationController
  include Commentable
  include Filterable
  before_action :authenticate_user!
  before_action :authorize_user
  before_action :set_user, except: %i[new create index]
  before_action :set_role_options, only: %i[new edit]

  # GET /admin/users
  def index
    @users = User.not_deleted.page params[:page]
    @users = filter_resource(@users)
    @users = UserDecorator.decorate_collection(@users).includes(:profile)
  end

  def show
    @commentable = @user
    prepare_comments
  end

  def new
    @user = User.new
  end

  def edit; end

  def edit_my_profile
    @form = EditUserProfileForm.new(current_user)
  end

  def update_my_profile
    @form = EditUserProfileForm.new(edit_my_profile_params.to_unsafe_h)
    if @form.update
      redirect_to [:admin, current_user], notice: 'Your profile was successfully updated.'
    else
      redirect_to edit_my_profile_admin_user_path, notice: @user.errors.full_messages
    end
  end

  def update
    if @user.update(user_params)
      redirect_to [:admin, current_user], notice: 'User was successfully updated.'
    else
      redirect_to edit_admin_user_path, alert: @user.errors.full_messages
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to admin_users_path, notice: 'User was successfully created.'
    else
      redirect_to new_admin_user_path, alert: @user.errors.full_messages
    end
  end

  # DELETE /admin/user/:id
  def destroy
    if @user.destroy
      redirect_to admin_users_path, notice: 'User was successfully destroyed.'
    else
      redirect_to admin_users_path, alert: @user.errors.full_messages
    end
  end

  private

  def authorize_user
    authorize [:admin, User]
  end

  def set_user
    @user = User.find(params[:id]).decorate
  end

  # Filters strong product params
  def user_params
    if current_user.admin?
      params.require(:user).permit(:email, :password, :password_confirmation, :role)
    elsif current_user.support?
      params.require(:user).permit(:email, :password, :password_confirmation)
    end
  end

  def set_role_options
    @role_options = User.role_options
    @role_options = [[@role_options[0], 0], [@role_options[2], 2]]
  end

  def search_params
    params.fetch(:search, {}).permit(:name, :tag)
  end

  # Filters filter(sorting) parameters
  def filter_param
    params.permit(:filter)
  end

  def edit_my_profile_params
    params.require(:edit_user_profile_form).permit(:email, :first_name, :last_name, :phone, :address)
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  include Commentable
  include Filterable
  before_action :authenticate_user!, except: %i[index show]
  before_action :authorize_user, except: %i[index show]
  before_action :set_user, except: %i[new create index]

  # GET /users
  def index
    @users = User.not_deleted.page params[:page]
    @users = filter_resource(@users)
    @users = UserDecorator.decorate_collection(@users).includes(:profile)
  end

  def show
    @commentable = @user
    prepare_comments
  end

  def edit_my_profile
    @form = EditUserProfileForm.new(current_user)
  end

  def update_my_profile
    @form = EditUserProfileForm.new(edit_my_profile_params.to_unsafe_h)
    if @form.update
      redirect_to current_user, notice: 'Your profile was successfully updated.'
    else
      redirect_to edit_my_profile_user_path, notice: @user.errors.full_messages
    end
  end

  private

  def authorize_user
    authorize User
  end

  def set_user
    @user = User.find(params[:id]).decorate
  end

  def search_params
    params.fetch(:search, {}).permit(:name, :tag)
  end

  def filter_param
    params.permit(:filter)
  end

  def edit_my_profile_params
    params.require(:edit_user_profile_form).permit(:email, :first_name, :last_name, :phone, :address)
  end
end

app/helpers/api/v1/users/registrations_helper.rb
# frozen_string_literal: true

module Api::V1::Users::RegistrationsHelper
end

app/views/admin/users/_search.html.erb
<%= form_for :search, method: :get, remote: true  do |f|%>
  <div class="ui fluid icon input">
      <%= link_to "Clear", admin_users_path, remote: true, class: 'negative ui button' %>
    <%= f.text_field :name, placeholder: "Search Users...", autofocus: true %>
    <i class="search icon"></i>
  </div>
<%end%>

app/views/admin/users/_user_card.html.erb
<div class="ui people shape">
  <div class="ui card">
    <div class="image"><img src=""></div>
    <div class="content">
      <div class="header">
      <%= link_to user.profile&.full_name || "Not Profiled", admin_user_path(user), class: "ui small header" %>
      </div>
      <div class="meta"> Joined <%= user.time_ago %> ago.</div>
      <div class="meta"><%= user.email %></div>
    </div>
    <div class="extra content">
      <span><i class="red heart icon"></i></span>
    </div>
    <div class="extra content">
      <span class="right floated">
        <% if !user.admin? && current_user.admin? %>
          <%= link_to 'Change Role', edit_admin_user_path(user), class: 'positive ui button' %>
          <%= link_to 'Destroy', admin_user_path(user), method: :delete, 
          data: { confirm: 'Are you sure?' }, class: 'negative ui button' %>
        <% end %>
        <% if user == current_user %>
          <%= link_to 'Settings', edit_my_profile_admin_user_path(current_user), class: 'positive ui button' %>
        <% end %>
      </span>
    </div>
  </div>
</div>

app/views/admin/users/edit.html.erb
<div class="ten wide column">
<h1><%= "#{@user.profile_first_name} #{@user.profile_last_name}"%></h1>
</div>
<div class="ten wide column">
<div class="ui form">
<%= form_for [:admin, @user] do |f| %>
  <div class="field">
    <%= f.label :role %><br />
    <%= f.select :role, @role_options, class: "ui dropdown"%>
  </div>

  <div class="actions">
    <%= f.submit "Update User", class: 'ui primary button' %>
  </div>
<% end %>

app/views/admin/users/edit_my_profile.html.erb
<div class="ten wide column">
<h1>Update My Profile</h1>
</div>
<div class="ten wide column">
<div class="ui form">
<%= form_for(@form, url: update_my_profile_admin_user_path, method: :put) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", required: true %>
  </div>

  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, autofocus: true, required: true %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, required: true  %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.phone_field :phone, required: true %>
  </div>

  <div class="field">
    <%= f.label :address %>
    <%= f.phone_field :address, required: true %>
  </div>

  <div class="actions">
    <%= f.submit "Update Profile", class: 'ui primary button' %>
  </div>
<% end %>

app/views/admin/users/index.html.erb
<div id="sidebar" class="two wide column">
</div>
<div class="fourteen wide column">
  <div class="item">
    <%= render partial: 'search' %>
  </div>
  <h1>Users</h1>
  <div id="grid">
    <%= render partial: "user_card", collection: @users, as: :user %>
  </div>
  <br>
  <div style="margin-left: 33%">
    <%= paginate @users, remote: true %>
  </div>
</div>

app/views/admin/users/index.js.erb
(function init() {
  document.querySelector('#grid').innerHTML =
    '<%= escape_javascript(render(partial: "user_card", collection: @users, as: :user)) %>';
})()

app/views/admin/users/new.html.erb
<div class="ten wide column">
<h1>New User</h1>
</div>
<div class="ten wide column">
<div class="ui form">
<%= form_for [:admin, @user] do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email, autofocus: true, autocomplete: "email", required: true %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <% if @minimum_password_length %>
    <em>(<%= @minimum_password_length %> characters minimum)</em>
    <% end %><br />
    <%= f.password_field :password, autocomplete: "new-password", required: true %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %><br />
    <%= f.password_field :password_confirmation, autocomplete: "new-password", required: true %>
  </div>
  <% if current_user.admin? %>
  <div class="field">
    <%= f.label :role %><br />
    <%= f.select :role, @role_options, class: "ui dropdown"%>
  </div>
  <% end %>
  <div class="actions">
    <%= f.submit "Create User", class: 'ui primary button' %>
  </div>
<% end %>
</div>
</div>

app/views/admin/users/show.html.erb
<div class="ten wide column">
<h1>User Details</h1>
</div>
<div class="ten wide column" id="profile">
  <%= render partial: "user_card", locals: {user: @user} %>
</div>
<div class="ten wide column ui comments">
  <h3 class="ui dividing header">Comments</h3>
  <div id="comments">
    <%= render partial: 'comments/comment_block', collection: @comments, as: :comment %>
  </div>
  <% if user_signed_in? %>
    <%= render partial: 'comments/comment_form' %>
  <% end %>
</div>
</div>